@Trip.WebApi_HostAddress = http://localhost:5048

GET {{Trip.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{Trip.WebApi_HostAddress}}/api/trips
Accept: application/json

###
GET {{Trip.WebApi_HostAddress}}/api/destinations/
Accept: application/json

###
POST {{Trip.WebApi_HostAddress}}/api/trips
Content-Type: application/json
Accept: application/json
{
    "name": "Summer Vacation 44 ",
    "startDate": "2024-07-01T00:00:00",
    "endDate": "2024-07-14T00:00:00",
    "destinationId": 3
}

###
POST {{Trip.WebApi_HostAddress}}/api/destinations
Content-Type: application/json
Accept: application/json
{
  "name": "Róma",
  "country": "Olasz",
  "description" :"bbbb"

}

###
PUT {{Trip.WebApi_HostAddress}}/api/trips/5
Content-Type: application/json
Accept: application/json
{
    "name": "Summer Vacation 21 ",
    "startDate": "2024-08-01T00:00:00",
    "endDate": "2024-09-14T00:00:00",
    "destinationId": 2
}

###
DELETE {{Trip.WebApi_HostAddress}}/api/trips/1
Content-Type: application/json

###
PUT {{Trip.WebApi_HostAddress}}/api/destinations/2
Content-Type: application/json
Accept: application/json
{
  "name": "Barca",
  "country": "Espanyol",
  "description" :"bba latinas"

}

###
DELETE {{Trip.WebApi_HostAddress}}/api/destinations/1
Content-Type: application/json